import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className>
      <Head>
        <title>Hulu Build</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* h1</h1> */}
      <h1></h1>
    </div>
  )
}
